### ISSUE TITLE
Multiple TreeNode Selector form controls affect each other

### ISSUE THREAD

**Issue by andybochmann** [heywills/xperience-treenode-selector-form-control#5]
Hey Mike. I noticed when placing two TreeNode Selector form controls on one page, they seem to affect each other after adding items.

Here is how I'm able to reproduce the problem:

1. On a page type, configure two TreeNode Selector form controls (they don't have to be right next to each other)
2. Select 1 item on the first and 2-3 items on the other. The exact number doesn't matter.

![image](https://github.com/heywills/xperience-treenode-selector-form-control/assets/11526609/fb668d4b-a24f-446f-9ce1-8e43967e9285)

3. Save the page to save the current state and be able to reproduce it again later
4. On the first selector, remove an item

![image](https://github.com/heywills/xperience-treenode-selector-form-control/assets/11526609/5a8b173f-5fc3-4fbe-b6ff-c99d4e040011)

5. Now click "Add items" on the second select
6. Without selecting anything, click the "Select" button to close the modal
7. Notice that the item in the first selector reappeared (same as first screenshot)

The items only reappear visually after the Postback of the modal. If you inspect the value of the `HiddenValue` input in JavaScript, you'll notice it's still empty. Therefore, saving the page will update the state and after a page reload the first selector has 0 items as expected.

Here are a few other things I noticed while investigating this issue.

When you click "Select" on step 6 to close the modal, notice that the network response to `edit.aspx` also includes the **Featured Products** `UpdatePanel`, even if I'm editing the **Related Applications** field. This response is causing the item to reappear in the first selector. Unfortunately, my WebForms knowledge is limited and I couldn't figure out how to prevent the additional `UpdatePanel` inside the response. It might have to be there by design, but I assumed that the response should only contain the second selector because that's the one I'm editing. 

![image](https://github.com/heywills/xperience-treenode-selector-form-control/assets/11526609/81db4f03-dacc-4a3a-a2df-5fc69bde0671)

As a temporary workaround, I've edited line 295 of **RelatedContentSelector.aspx.cs** and removed the `if (!IsPostBack)` condition to always initialize the items. This seems to reinitialize the list with the correct items. Not sure if my change might have other unforeseen consequences, but it seems to work fine so far.

![image](https://github.com/heywills/xperience-treenode-selector-form-control/assets/11526609/f974085e-f3c5-4918-8d46-9444fae41c3e)

Please let me know if you need any other information or would like me to test something.

**Comment by bluemodus-mwills** [comment]
@andybochmann -- thank you. This is excellent detail. Thanks for doing all the ground work for figuring out the problem too. I'll publish a fix soon.

**Comment by bluemodus-mwills** [comment]
@andybochmann - I created an official fix, including multiple performance optimizations to take the pain out of initializing the control every time a postback occurs. It's available in XperienceCommunity.TreeNodeSelectorFormControl version 1.0.7.

**Comment by andybochmann** [comment]
@bluemodus-mwills Wonderful, thank you so much!
