### ISSUE TITLE
JavaScript exception caused by OnSiteEdit.js file

### ISSUE THREAD

**Issue by andybochmann** [heywills/xperience-treenode-selector-form-control#6]
This is not directly an issue with this TreeNode Selector Form Control, but it's indirectly causing the following problem that I'd like to mention in case you have another workaround or solution.

The TreeNode selector form control is registering the `DesignMode/OnSiteEdit.js` file on the page.

That `OnSiteEdit.js` script references a variable called "OEIsMobile" in a few places, however, I don't see this variable being defined anywhere. Because the variable isn't defined, the browser will throw an exception and stop executing the rest of the code, which causes additional problems.

![image](https://github.com/heywills/xperience-treenode-selector-form-control/assets/11526609/91e8ace2-a505-4128-aefe-33684efca25a)

We noticed the exception after adding the TreeNode Selector Form Control to a page type and editing the page's Content tab. At first, it seemed to cause no harm, however, after also adding two FileUploader form controls to the same page type, we noticed the FileUploader form controls weren't working correctly anymore. It basically means that you can not have two FileSelector form controls and a TreeNode Selector form control on the same page.

I added the following code to the top of `OnSiteEdit.js` to solve the problem.

```
// check if OEIsMobile is defined, if not set it to false
if (typeof OEIsMobile == 'undefined') {
   window.OEIsMobile = false;
}
```

I did report the issue to Kentico, however, they are not willing to resolve it. Kentico itself no longer seems to depend on `OnSiteEdit.js` and therefore won't see the issue out-of-the-box.

**Comment by bluemodus-mwills** [comment]
Thank you @andybochmann -- again, for providing so much detail and doing the legwork to figure out the problem. I'll publish a fix soon.

**Comment by bluemodus-mwills** [comment]
@andybochmann - You've been so patient. I created a fix for this too, which doesn't require modifying Kentico's out-of-the-box script file. It's available in XperienceCommunity.TreeNodeSelectorFormControl version 1.0.7.

**Comment by andybochmann** [comment]
@bluemodus-mwills Thank you again, that's great! I will give the new version a try.
